version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'timetrackdev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --lower_case_table_names=1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.data:/var/lib/mysql
